In [13]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense

In [3]:
data = load_breast_cancer()

In [19]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [6]:
data['data'].shape

(569, 30)

In [7]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [18]:
feature = data['data']
feature

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [16]:
label = data['target']
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
scale = StandardScaler()
feature = scale.fit_transform(feature)

In [21]:
feature

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [25]:
df_ft = pd.DataFrame(feature, columns = data['feature_names'])
df_lab = pd.DataFrame(label, columns = ['label'])
df = pd.concat([df_ft, df_lab], axis=1)
df = df.sample(frac = 1)

feature = df.values[ :, : 30]
label = df.values[: , 30: ]

In [26]:
df

mean radius  mean texture  ...  worst fractal dimension  label
173    -0.865474     -1.065715  ...                -0.599367      1
559    -0.743348      1.079841  ...                 0.186983      1
330     0.540396     -0.879550  ...                 0.404213      0
326    -0.004911     -1.491568  ...                -0.726824      1
406     0.571638     -1.030809  ...                -0.766169      1
..           ...           ...  ...                      ...    ...
125    -0.078755     -0.483948  ...                -0.671962      1
18      1.613970      0.665623  ...                -0.432012      0
459    -1.241793      2.073499  ...                -0.655891      1
532    -0.127037     -0.688730  ...                -0.339467      1
551    -0.851273      0.733108  ...                -0.200928      1

[569 rows x 31 columns]

In [28]:
X_train, X_rem, y_train, y_rem = train_test_split(feature, label, train_size=0.8)
X_val, X_test, y_val, y_test = train_test_split(X_rem, y_rem, train_size=0.5)

In [34]:
model = Sequential()

model.add(Dense(15, activation='relu', input_dim=30))
model.add(Dense(10, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=2, validation_data=(X_val, y_val))


Epoch 1/10
228/228 [==============================] - 1s 2ms/step - loss: 0.4144 - accuracy: 0.8286 - val_loss: 0.2617 - val_accuracy: 0.9298
Epoch 2/10
228/228 [==============================] - 0s 2ms/step - loss: 0.1640 - accuracy: 0.9560 - val_loss: 0.2375 - val_accuracy: 0.9298
Epoch 3/10
228/228 [==============================] - 0s 2ms/step - loss: 0.0872 - accuracy: 0.9714 - val_loss: 0.2453 - val_accuracy: 0.9298
Epoch 4/10
228/228 [==============================] - 0s 2ms/step - loss: 0.0670 - accuracy: 0.9780 - val_loss: 0.2659 - val_accuracy: 0.9298
Epoch 5/10
228/228 [==============================] - 0s 2ms/step - loss: 0.0534 - accuracy: 0.9846 - val_loss: 0.2866 - val_accuracy: 0.9474
Epoch 6/10
228/228 [==============================] - 0s 1ms/step - loss: 0.0464 - accuracy: 0.9868 - val_loss: 0.2934 - val_accuracy: 0.9474
Epoch 7/10
228/228 [==============================] - 0s 2ms/step - loss: 0.0388 - accuracy: 0.9890 - val_loss: 0.2845 - val_accuracy: 0.9474
Epoch 

In [35]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.0011 - accuracy: 1.0000


[0.0010891385609284043, 1.0]